"""Tests for Story 10.1 — Bug fix: POST /api/upload unified endpoint.

Covers:
1. POST /api/upload with PDF + XSD → 200 + {"job_id": uuid}
2. POST /api/upload without XSD → 422 Unprocessable Entity
3. POST /api/upload with PDF + XSD + data → 200 + {"job_id": uuid}
"""

from __future__ import annotations

import base64
import io
import re
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# ---------------------------------------------------------------------------
# App import
# ---------------------------------------------------------------------------
from main import app

pytestmark = pytest.mark.integration

client = TestClient(app)

_UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$")

# ---------------------------------------------------------------------------
# Minimal valid byte content for each file type
# ---------------------------------------------------------------------------

# Minimal valid PDF generated by PyMuPDF (1 page, 595x842)
_PDF_BYTES = base64.b64decode(
    "JVBERi0xLjcKJcK1wrYKJSBXcml0dGVuIGJ5IE11UERGIDEuMjcuMgoKMSAwIG9iago8PC9UeXBl"
    "L0NhdGFsb2cvUGFnZXMgMiAwIFIvSW5mbzw8L1Byb2R1Y2VyKE11UERGIDEuMjcuMik+Pj4+CmVu"
    "ZG9iagoKMiAwIG9iago8PC9UeXBlL1BhZ2VzL0NvdW50IDEvS2lkc1s0IDAgUl0+PgplbmRvYmoK"
    "CjMgMCBvYmoKPDwvRm9udDw8L2hlbHYgNSAwIFI+Pj4+CmVuZG9iagoKNCAwIG9iago8PC9UeXBl"
    "L1BhZ2UvTWVkaWFCb3hbMCAwIDU5NSA4NDJdL1JvdGF0ZSAwL1Jlc291cmNlcyAzIDAgUi9QYXJl"
    "bnQgMiAwIFIvQ29udGVudHNbNiAwIFJdPj4KZW5kb2JqCgo1IDAgb2JqCjw8L1R5cGUvRm9udC9T"
    "dWJ0eXBlL1R5cGUxL0Jhc2VGb250L0hlbHZldGljYS9FbmNvZGluZy9XaW5BbnNpRW5jb2Rpbmc+"
    "PgplbmRvYmoKCjYgMCBvYmoKPDwvTGVuZ3RoIDU2Pj4Kc3RyZWFtCgpxCkJUCjEgMCAwIDEgNzIg"
    "NzcwIFRtCi9oZWx2IDExIFRmIFs8NzQ2NTczNzQ+XVRKCkVUClEKCmVuZHN0cmVhbQplbmRvYmoK"
    "CnhyZWYKMCA3CjAwMDAwMDAwMDAgNjU1MzUgZiAKMDAwMDAwMDA0MiAwMDAwMCBuIAowMDAwMDAw"
    "MTIwIDAwMDAwIG4gCjAwMDAwMDAxNzIgMDAwMDAgbiAKMDAwMDAwMDIxMyAwMDAwMCBuIAowMMDAwM"
    "DAzMjAgMDAwMDAgbiAKMDAwMDAwMDQwOSAwMDAwMCBuIAoKdHJhaWxlcgo8PC9TaXplIDcvUm9vdC"
    "AxIDAgUi9JRFs8MjVDMkFCMTlDM0I0QzNCN0MyOEQ2ODQxNTFDM0JGMzc+PEZBMkM5NzM4MzkxNEU4"
    "RDA5MTg4MDk1NzJBRTQyQUQxPl0+PgpzdGFydHhyZWYKNTE0CiUlRU9GCg=="
)
_XSD_BYTES = b'<?xml version="1.0"?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"></xs:schema>'
_XML_BYTES = b'<?xml version="1.0"?><root><field>value</field></root>'
_JSON_BYTES = b'{"field": "value"}'


def _pdf_file(name: str = "input.pdf") -> tuple[str, tuple]:
    return ("pdfs[]", (name, io.BytesIO(_PDF_BYTES), "application/pdf"))


def _xsd_file(name: str = "schema.xsd") -> tuple[str, tuple]:
    return ("xsd", (name, io.BytesIO(_XSD_BYTES), "text/xml"))


def _xml_data_file(name: str = "data.xml") -> tuple[str, tuple]:
    return ("data", (name, io.BytesIO(_XML_BYTES), "text/xml"))


def _json_data_file(name: str = "data.json") -> tuple[str, tuple]:
    return ("data", (name, io.BytesIO(_JSON_BYTES), "application/json"))


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


class TestUploadUnified:
    """Test suite for POST /api/upload."""

    def test_pdf_and_xsd_returns_200_with_job_id(self) -> None:
        """Scenario 1: PDF + XSD → 200 + {job_id: uuid}."""
        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file()],
            data={"template_name": "Test Template"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert "job_id" in body, f"Expected 'job_id' in response, got: {body}"
        job_id = body["job_id"]
        assert _UUID_RE.match(job_id.lower()), f"job_id is not a valid UUID v4: {job_id}"

    def test_missing_xsd_returns_422(self) -> None:
        """Scenario 2: No XSD → 422 Unprocessable Entity."""
        response = client.post(
            "/api/upload",
            files=[_pdf_file()],
            data={"template_name": "Test Template"},
        )
        assert response.status_code == 422, f"Expected 422, got {response.status_code}: {response.text}"

    def test_pdf_xsd_and_xml_data_returns_200_with_job_id(self) -> None:
        """Scenario 3: PDF + XSD + XML data → 200 + {job_id: uuid}."""
        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file(), _xml_data_file()],
            data={"template_name": "Test Template"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert "job_id" in body
        assert _UUID_RE.match(body["job_id"].lower())

    def test_pdf_xsd_and_json_data_returns_200_with_job_id(self) -> None:
        """Scenario 3b: PDF + XSD + JSON data → 200 + {job_id: uuid}."""
        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file(), _json_data_file()],
            data={"template_name": "Test Template"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert "job_id" in body
        assert _UUID_RE.match(body["job_id"].lower())

    def test_multiple_pdfs_returns_200_with_job_id(self) -> None:
        """Multiple PDFs (pdf_2, pdf_3) should all be accepted."""
        response = client.post(
            "/api/upload",
            files=[
                _pdf_file("doc1.pdf"),
                _pdf_file("doc2.pdf"),
                _pdf_file("doc3.pdf"),
                _xsd_file(),
            ],
            data={"template_name": "Multi PDF Test"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert "job_id" in body
        assert _UUID_RE.match(body["job_id"].lower())

    def test_upload_returns_template_name_in_response(self) -> None:
        """Story 38.6: upload response includes template_name."""
        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file()],
            data={"template_name": "Extrato Bancario"},
        )
        assert response.status_code == 200, response.text
        body = response.json()
        assert body.get("template_name") == "Extrato Bancario"

    def test_upload_persists_template_name_as_metadata(self) -> None:
        """Story 38.6: template_name is persisted as assets/template_name.txt."""
        from routers.upload import TMP_BASE

        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file()],
            data={"template_name": "Nota Fiscal"},
        )
        assert response.status_code == 200
        job_id = response.json()["job_id"]
        meta_path = TMP_BASE / job_id / "assets" / "template_name.txt"
        assert meta_path.exists(), f"template_name.txt not found at {meta_path}"
        assert meta_path.read_text(encoding="utf-8") == "Nota Fiscal"

    def test_upload_empty_template_name_no_metadata_file(self) -> None:
        """Story 38.6: empty template_name does not create metadata file."""
        from routers.upload import TMP_BASE

        response = client.post(
            "/api/upload",
            files=[_pdf_file(), _xsd_file()],
            data={"template_name": ""},
        )
        assert response.status_code == 200
        job_id = response.json()["job_id"]
        meta_path = TMP_BASE / job_id / "assets" / "template_name.txt"
        assert not meta_path.exists(), "template_name.txt should not exist for empty name"

    # ── TD-38.2: template_name sanitization ────────────────────────────────

    def test_template_name_html_stripped(self, tmp_path: Path) -> None:
        """HTML tags in template_name must be stripped."""
        from routers.upload import sanitize_template_name

        assert sanitize_template_name("<script>alert(1)</script>MyTemplate") == "alert1MyTemplate"
        assert sanitize_template_name("<b>Bold</b> Name") == "Bold Name"
        assert sanitize_template_name("Clean Name") == "Clean Name"

    def test_template_name_special_chars_removed(self, tmp_path: Path) -> None:
        """Special characters outside allowed charset are removed."""
        from routers.upload import sanitize_template_name

        assert sanitize_template_name("My Template!@#$%") == "My Template"
        assert sanitize_template_name("valid-name_123.pdf") == "valid-name_123.pdf"

    def test_template_name_max_length(self, tmp_path: Path) -> None:
        """template_name must be truncated to 100 chars."""
        from routers.upload import sanitize_template_name

        long_name = "A" * 200
        assert len(sanitize_template_name(long_name)) == 100

    def test_template_name_whitespace_collapsed(self, tmp_path: Path) -> None:
        """Multiple spaces must be collapsed to single space."""
        from routers.upload import sanitize_template_name

        assert sanitize_template_name("  Hello    World  ") == "Hello World"

    def test_legacy_endpoints_still_exist(self) -> None:
        """Legacy endpoints must NOT be removed (backward compatibility)."""
        # POST /api/upload/pdf
        pdf_response = client.post(
            "/api/upload/pdf",
            files=[("file", ("test.pdf", io.BytesIO(_PDF_BYTES), "application/pdf"))],
        )
        # We only check it doesn't 404
        assert pdf_response.status_code != 404, "Legacy /api/upload/pdf was removed"
